<a href="https://colab.research.google.com/github/KashafGull123/OIBSIP-/blob/main/DataAnalytics-L1-CleaningData/internship_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import pandas for data manipulation
import pandas as pd

# Import numpy for numerical operations
import numpy as np

In [ ]:
# Load Excel dataset
df = pd.read_csv("/content/fifa21_raw_data.csv")

# Display first five rows
df.head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33.0,93.0,93.0,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85.0,92.0,91.0,95.0,38.0,65.0,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35.0,92.0,92.0,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89.0,93.0,81.0,89.0,35.0,77.0,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27.0,91.0,93.0,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87.0,92.0,78.0,90.0,52.0,90.0,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29.0,91.0,91.0,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76.0,86.0,93.0,88.0,64.0,78.0,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28.0,91.0,91.0,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91.0,85.0,86.0,94.0,36.0,59.0,\n273

In [ ]:
# Display first five rows
df.head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33.0,93.0,93.0,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85.0,92.0,91.0,95.0,38.0,65.0,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35.0,92.0,92.0,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89.0,93.0,81.0,89.0,35.0,77.0,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27.0,91.0,93.0,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87.0,92.0,78.0,90.0,52.0,90.0,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29.0,91.0,91.0,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76.0,86.0,93.0,88.0,64.0,78.0,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28.0,91.0,91.0,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91.0,85.0,86.0,94.0,36.0,59.0,\n273

In [ ]:
# Display number of rows and columns
print("Rows and Columns:", df.shape)

Rows and Columns: (16038, 77)

In [ ]:
# Show all column names
print(df.columns.tolist())

['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name', 'Age', '↓OVA', 'POT', 'Team & Contract', 'ID', 'Height', 'Weight', 'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits']

In [ ]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16038 entries, 0 to 16037
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          16038 non-null  object
 1   LongName          16038 non-null  object
 2   playerUrl         16038 non-null  object
 3   Nationality       16037 non-null  object
 4   Positions         16037 non-null  object
 5   Name              16037 non-null  object
 6   Age               16037 non-null  float64
 7   ↓OVA              16037 non-null  float64
 8   POT               16037 non-null  float64
 9   Team & Contract   16037 non-null  object
 10  ID                16037 non-null  float64
 11  Height            16037 non-null  object
 12  Weight            16037 non-null  object
 13  foot              16037 non-null  object
 14  BOV               16037 non-null  float64
 15  BP                16037 non-null  object
 16  Growth            16037 non-null  float64
 17  Joined            16037 non-null  object
 18  Loan Date End     918 non-null    object
 19  Value             16037 non-null  object
 20  Wage              16037 non-null  object
 21  Release Clause    16037 non-null  object
 22  Attacking         16037 non-null  float64
 23  Crossing          16037 non-null  float64
 24  Finishing         16037 non-null  float64
 25  Heading Accuracy  16037 non-null  float64
 26  Short Passing     16037 non-null  float64
 27  Volleys           16037 non-null  float64
 28  Skill             16037 non-null  float64
 29  Dribbling         16037 non-null  float64
 30  Curve             16037 non-null  float64
 31  FK Accuracy       16037 non-null  float64
 32  Long Passing      16037 non-null  float64
 33  Ball Control      16037 non-null  float64
 34  Movement          16037 non-null  float64
 35  Acceleration      16037 non-null  float64
 36  Sprint Speed      16037 non-null  float64
 37  Agility           16037 non-null  float64
 38  Reactions         16037 non-null  float64
 39  Balance           16037 non-null  float64
 40  Power             16037 non-null  float64
 41  Shot Power        16037 non-null  float64
 42  Jumping           16037 non-null  float64
 43  Stamina           16037 non-null  float64
 44  Strength          16037 non-null  float64
 45  Long Shots        16037 non-null  float64
 46  Mentality         16037 non-null  float64
 47  Aggression        16037 non-null  float64
 48  Interceptions     16037 non-null  float64
 49  Positioning       16037 non-null  float64
 50  Vision            16037 non-null  float64
 51  Penalties         16037 non-null  float64
 52  Composure         16037 non-null  float64
 53  Defending         16037 non-null  float64
 54  Marking           16037 non-null  float64
 55  Standing Tackle   16037 non-null  float64
 56  Sliding Tackle    16037 non-null  float64
 57  Goalkeeping       16037 non-null  float64
 58  GK Diving         16037 non-null  float64
 59  GK Handling       16037 non-null  float64
 60  GK Kicking        16037 non-null  float64
 61  GK Positioning    16037 non-null  float64
 62  GK Reflexes       16037 non-null  float64
 63  Total Stats       16037 non-null  float64
 64  Base Stats        16037 non-null  float64
 65  W/F               16037 non-null  object
 66  SM                16037 non-null  object
 67  A/W               16037 non-null  object
 68  D/W               16037 non-null  object
 69  IR                16037 non-null  object
 70  PAC               16037 non-null  float64
 71  SHO               16037 non-null  float64
 72  PAS               16037 non-null  float64
 73  DRI               16037 non-null  float64
 74  DEF               16037 non-null  float64
 75  PHY               16037 non-null  float64
 76  Hits              16037 non-null  object
dtypes: float64(55), object(22)
memory usage: 9.4+ MB

In [ ]:
# Count missing values in each column
null_values = df.isnull().sum()

print(null_values)

photoUrl       0
LongName       0
playerUrl      0
Nationality    1
Positions      1
              ..
PAS            1
DRI            1
DEF            1
PHY            1
Hits           1
Length: 77, dtype: int64

In [ ]:
# Count duplicate rows
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 1

In [ ]:
# Display data types
print(df.dtypes)

photoUrl        object
LongName        object
playerUrl       object
Nationality     object
Positions       object
                ...
PAS            float64
DRI            float64
DEF            float64
PHY            float64
Hits            object
Length: 77, dtype: object

In [ ]:
# Create Data Quality Report

quality_report = pd.DataFrame({

    "Data Type": df.dtypes,

    "Missing Values": df.isnull().sum(),

    "Unique Values": df.nunique()

})

quality_report

            Data Type  Missing Values  Unique Values
photoUrl       object               0          16037
LongName       object               0          15944
playerUrl      object               0          16037
Nationality    object               1            160
Positions      object               1            623
...               ...             ...            ...
PAS           float64               1             65
DRI           float64               1             66
DEF           float64               1             78
PHY           float64               1             62
Hits           object               1            373

[77 rows x 3 columns]

In [ ]:
# Calculate percentage of missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100

# Create a DataFrame
missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": missing_percentage
})

# Display only columns having missing values
missing_report[missing_report["Missing Values"] > 0]

             Missing Values  Percentage
Nationality               1    0.006235
Positions                 1    0.006235
Name                      1    0.006235
Age                       1    0.006235
↓OVA                      1    0.006235
...                     ...         ...
PAS                       1    0.006235
DRI                       1    0.006235
DEF                       1    0.006235
PHY                       1    0.006235
Hits                      1    0.006235

[74 rows x 2 columns]

In [ ]:
# Remove columns where all values are missing
df = df.dropna(axis=1, how="all")

In [ ]:
# Select numerical columns
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

# Fill missing values with median
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
# Select categorical columns
categorical_cols = df.select_dtypes(include="object").columns

# Fill missing values with mode
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

Reason:

Mode was used because it replaces missing values with the most frequent category.

In [ ]:
# Verify missing values after cleaning
print(df.isnull().sum())

photoUrl       0
LongName       0
playerUrl      0
Nationality    0
Positions      0
              ..
PAS            0
DRI            0
DEF            0
PHY            0
Hits           0
Length: 77, dtype: int64

In [ ]:
# Count duplicates before removal
duplicates_before = df.duplicated().sum()

print("Duplicate Rows Before:", duplicates_before)

# Remove duplicate rows
df = df.drop_duplicates()

# Count duplicates after removal
duplicates_after = df.duplicated().sum()

print("Duplicate Rows After:", duplicates_after)

Duplicate Rows Before: 1
Duplicate Rows After: 0

Observation:

Duplicate records were removed to improve data quality and avoid repeated information.

In [ ]:
# Remove leading and trailing spaces from text columns
for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip()

In [ ]:
# Convert text into Title Case
for col in categorical_cols:
    df[col] = df[col].str.title()

Observation:

Text values were standardized by removing extra spaces and converting them to title case.

In [ ]:
# Check unique values
df["Value"].head()

0    €67.5M
1      €46M
2      €75M
3      €87M
4      €90M
Name: Value, dtype: object

In [ ]:
# Function to convert Value into numbers
def convert_value(value):

    if pd.isna(value):
        return np.nan

    value = str(value).replace("€", "")

    if "M" in value:
        return float(value.replace("M", "")) * 1000000

    elif "K" in value:
        return float(value.replace("K", "")) * 1000

    else:
        return float(value)

# Apply function
df["Value"] = df["Value"].apply(convert_value)

# Check result
df["Value"].head()

0    67500000.0
1    46000000.0
2    75000000.0
3    87000000.0
4    90000000.0
Name: Value, dtype: float64

Observation:

The Value column contained currency symbols (€) and abbreviations (M, K). These were converted into numeric values for analysis.

In [ ]:
# Function to clean Wage column
def convert_wage(value):

    if pd.isna(value):
        return np.nan

    value = str(value).replace("€", "")

    if "M" in value:
        return float(value.replace("M", "")) * 1000000

    elif "K" in value:
        return float(value.replace("K", "")) * 1000

    else:
        return float(value)

# Apply function
df["Wage"] = df["Wage"].apply(convert_wage)

# Check result
df["Wage"].head()

0    560000.0
1    220000.0
2    125000.0
3    370000.0
4    270000.0
Name: Wage, dtype: float64

In [ ]:
# Apply same function
df["Release Clause"] = df["Release Clause"].apply(convert_value)

# Display first rows
df["Release Clause"].head()

0    138400000.0
1     75900000.0
2    159400000.0
3    161000000.0
4    166500000.0
Name: Release Clause, dtype: float64

In [ ]:
# Remove cm symbol and convert to integer
df["Height"] = df["Height"].str.replace("cm", "", regex=False)

df["Height"] = pd.to_numeric(df["Height"])

ValueError: Unable to parse string "5'7"" at position 0

In [ ]:
# Remove kg symbol
df["Weight"] = df["Weight"].str.replace("kg", "", regex=False)

# Convert into numeric
df["Weight"] = pd.to_numeric(df["Weight"])

ValueError: Unable to parse string "159Lbs" at position 0

In [ ]:
# Convert Joined into datetime
df["Joined"] = pd.to_datetime(df["Joined"], errors="coerce")

# Check datatype
df["Joined"].dtype

dtype('<M8[ns]')

In [ ]:
# Function to convert Hits
def clean_hits(value):

    if pd.isna(value):
        return np.nan

    value = str(value)

    if "K" in value:
        return float(value.replace("K", "")) * 1000

    else:
        return float(value)

# Apply function
df["Hits"] = df["Hits"].apply(clean_hits)

In [ ]:
# Display updated data types
print(df.dtypes)

photoUrl        object
LongName        object
playerUrl       object
Nationality     object
Positions       object
                ...
PAS            float64
DRI            float64
DEF            float64
PHY            float64
Hits           float64
Length: 77, dtype: object

Observation:

The Value, Wage, Release Clause, Height, Weight, Joined, and Hits columns were successfully converted into appropriate numeric and datetime formats. This makes the dataset suitable for further analysis and machine learning.

In [ ]:
# Select numeric columns
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

# Check number of outliers in each numeric column
for col in numeric_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - (1.5 * IQR)
    upper = Q3 + (1.5 * IQR)

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

Age: 24 outliers
↓OVA: 142 outliers
POT: 62 outliers
ID: 200 outliers
BOV: 128 outliers
Growth: 206 outliers
Value: 2156 outliers
Wage: 1833 outliers
Release Clause: 2243 outliers
Attacking: 1627 outliers
Crossing: 10 outliers
Finishing: 0 outliers
Heading Accuracy: 1306 outliers
Short Passing: 1546 outliers
Volleys: 0 outliers
Skill: 1468 outliers
Dribbling: 1739 outliers
Curve: 0 outliers
FK Accuracy: 0 outliers
Long Passing: 320 outliers
Ball Control: 1746 outliers
Movement: 433 outliers
Acceleration: 569 outliers
Sprint Speed: 514 outliers
Agility: 218 outliers
Reactions: 111 outliers
Balance: 192 outliers
Power: 277 outliers
Shot Power: 2 outliers
Jumping: 195 outliers
Stamina: 1371 outliers
Strength: 228 outliers
Long Shots: 0 outliers
Mentality: 1489 outliers
Aggression: 11 outliers
Interceptions: 0 outliers
Positioning: 146 outliers
Vision: 101 outliers
Penalties: 7 outliers
Composure: 382 outliers
Defending: 0 outliers
Marking: 0 outliers
Standing Tackle: 0 outliers
Sliding Tackle: 0 outliers
Goalkeeping: 1694 outliers
GK Diving: 1622 outliers
GK Handling: 1622 outliers
GK Kicking: 1626 outliers
GK Positioning: 1623 outliers
GK Reflexes: 1622 outliers
Total Stats: 832 outliers
Base Stats: 87 outliers
PAC: 564 outliers
SHO: 3 outliers
PAS: 149 outliers
DRI: 564 outliers
DEF: 0 outliers
PHY: 298 outliers
Hits: 2055 outliers

## Outlier Detection

Outliers were detected using the IQR (Interquartile Range) method. Instead of removing all outliers automatically, they were first identified and evaluated because some extreme values may represent real football players with exceptional performance or market value.

In [ ]:
# Cap outliers using IQR limits

for col in numeric_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - (1.5 * IQR)
    upper = Q3 + (1.5 * IQR)

    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

## Outlier Treatment

Instead of removing outliers, extreme values were capped using the IQR boundaries. This preserves all player records while reducing the influence of extreme values.

In [ ]:
# Check final data types
df.dtypes

photoUrl        object
LongName        object
playerUrl       object
Nationality     object
Positions       object
                ...
PAS            float64
DRI            float64
DEF            float64
PHY            float64
Hits           float64
Length: 77, dtype: object

In [ ]:
before = pd.read_csv("fifa21_raw_data.csv", low_memory=False)

summary = pd.DataFrame({

    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows"
    ],

    "Before": [
        before.shape[0],
        before.shape[1],
        before.isnull().sum().sum(),
        before.duplicated().sum()
    ],

    "After": [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]

})

summary

           Metric  Before  After
0            Rows   18979  16037
1         Columns      77     77
2  Missing Values   17966      0
3  Duplicate Rows       1      0

In [ ]:
quality_report = pd.DataFrame({

    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values

})

quality_report

         Column Data Type  Missing Values  Unique Values
0      photoUrl    object               0          16037
1      LongName    object               0          15944
2     playerUrl    object               0          16037
3   Nationality    object               0            160
4     Positions    object               0            623
..          ...       ...             ...            ...
72          PAS   float64               0             49
73          DRI   float64               0             46
74          DEF   float64               0             78
75          PHY   float64               0             46
76         Hits   float64               0             27

[77 rows x 4 columns]

In [ ]:
# Save cleaned dataset

df.to_csv("cleaned_fifa21.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
from google.colab import files

files.download("cleaned_fifa21.csv")

# Conclusion

The FIFA 21 raw dataset was successfully cleaned and prepared for analysis.

The cleaning process included:

- Loading and inspecting the dataset.
- Generating a data quality report.
- Handling missing values using median and mode imputation.
- Removing duplicate records.
- Standardizing text formatting.
- Correcting incorrect data types.
- Cleaning Value, Wage, Release Clause, Height, Weight, Joined, and Hits columns.
- Detecting and treating outliers using the IQR method.
- Creating a before vs. after summary.
- Exporting the cleaned dataset to a new CSV file.

The final dataset is clean, consistent, and ready for exploratory data analysis or machine learning.